### ISSUE TITLE
dialout group required to access ttyUSB devices

### ISSUE THREAD

**Issue by DavesCodeMusings** [DavesCodeMusings/school-coding-lab#26]
admin, student, and any other users on the system need to be members of the dialout group to interact with USB-attached microcontrollers.

Should be in configure_dev_workstation.yml

```
    - name: Add user ids to groups
      ansible.builtin.user:
        name: "{{ item }}"
        groups: vnc, www-data
        append: yes
      with_items:
        - "{{ admin_login_id }}"
        - "{{ student_login_id }}"
```
